name: Mono-Repo Deployment
on: 
  push:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Boto3
        run: pip install boto3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run deployment script
        env:
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME:  ${{ github.ref_name }}
          DEVELOPER: ${{ github.actor }}
          S3_BUCKET_DEV: ${{ vars.S3_BUCKET_DEV }}
          S3_BUCKET_QA: ${{ vars.S3_BUCKET_QA }}
          S3_BUCKET_PROD: ${{ vars.S3_BUCKET_PROD }}
        run: python build_scripts/deploy_lambdas.py